export const LICENSES = [
  {
    id: 'ipe',
    name: '정보처리산업기사',
    level: '',
    issuer: '한국산업인력공단',
    acquiredAt: '2022-09-02',
    expiresAt: null,
    score: null,
    status: 'obtained',
    notes: '',
  },
  {
    id: 'cpa1',
    name: '컴퓨터활용능력',
    level: '1급',
    issuer: '대한상공회의소',
    acquiredAt: '2022-12-16',
    expiresAt: null,
    score: null,
    status: 'obtained',
    notes: '',
  },
  {
    id: 'khs2',
    name: '한국사능력검정',
    level: '2급',
    issuer: '국사편찬위원회',
    acquiredAt: '2024-02-29',
    expiresAt: null,
    score: null,
    status: 'obtained',
    notes: '',
  },
  {
    id: 'eip',
    name: '정보처리기사',
    level: '',
    issuer: '한국산업인력공단',
    acquiredAt: null,
    expiresAt: null,
    score: null,
    status: 'preparing',
    notes: '필기 합격/실기 준비중',
  },
  {
    id: 'toeic',
    name: 'TOEIC',
    level: '',
    issuer: 'ETS',
    acquiredAt: '',
    expiresAt: '',
    score: null,
    credentialUrl: '',
    status: 'preparing',
    notes: '준비중',
  },
];
